pm uninstall -k --user 0 com.samsung.android.samsungpassautofill
pm uninstall -k --user 0 com.google.ar.core
pm uninstall -k --user 0 com.samsung.android.arzone
pm uninstall -k --user 0 com.sec.android.mimage.avatarstickers
pm uninstall -k --user 0 com.samsung.android.aremojieditor
pm uninstall -k --user 0 com.samsung.android.aremoji
pm uninstall -k --user 0 com.samsung.android.ardrawing
pm uninstall -k --user 0 com.samsung.android.visionarapps
pm uninstall -k --user 0 com.samsung.android.samsungpassautofill
pm uninstall -k --user 0 com.samsung.android.app.routines
pm uninstall -k --user 0 com.samsung.android.bixby.service
pm uninstall -k --user 0 com.samsung.android.bixby.agent
pm uninstall -k --user 0 com.samsung.android.bixby.agent.dummy
pm uninstall -k --user 0 com.samsung.android.calendar
pm uninstall -k --user 0 com.samsung.android.beaconmanager
pm uninstall -k --user 0 com.google.android.projection.gearhead
pm uninstall -k --user 0 com.samsung.android.app.appsegde
pm uninstall -k --user 0 com.sec.android.app.popupcalculator
pm uninstall -k --user 0 com.samsung.android.app.cocktailbarservice
pm uninstall -k --user 0 com.facebook.katana
pm uninstall -k --user 0 com.facebook.system
pm uninstall -k --user 0 com.samsung.android.game.gametools
pm uninstall -k --user 0 com.samsung.android.game.gamehome
pm uninstall -k --user 0 com.samsung.android.game.gos
pm uninstall -k --user 0 com.google.android.googlequicksearchbox
pm uninstall -k --user 0 com.sec.android.service.health
pm uninstall -k --user 0 com.sec.android.cover.ledcover
pm uninstall -k --user 0 com.samsung.android.mdx
pm uninstall -k --user 0 com.android.hotwordenrollment.okgoogle
pm uninstall -k --user 0 com.microsoft.skydrive
pm uninstall -k --user 0 com.netflix.partner.activation
pm uninstall -k --user 0 com.samsung.android.app.reminder
pm uninstall -k --user 0 com.samsung.android.scloud
pm uninstall -k --user 0 com.samsung.android.app.spage
pm uninstall -k --user 0 com.samsung.android.mateagent
pm uninstall -k --user 0 com.samsung.android.app.sbrowseredge
pm uninstall -k --user 0 com.samsung.android.kidsinstaller
pm uninstall -k --user 0 com.sec.location.nsflp2
pm uninstall -k --user 0 com.samsung.android.samsungpass
pm uninstall -k --user 0 com.samsug.android.spayfw
pm uninstall -k --user 0 com.sec.spp.push
pm uninstall -k --user 0 com.samsung.knox.securefolder
pm uninstall -k --user 0 com.samsung.android.fast
pm uninstall -k --user 0 com.samsung.android.app.settings.bixby
pm uninstall -k --user 0 com.samsung.android.stickercenter
pm uninstall -k --user 0 com.samsung.systemui.bixby2
pm uninstall -k --user 0 com.samsung.android.app.tips
pm uninstall -k --user 0 de.axelspringer.yana.zeropage
pm uninstall -k --user 0 com.sec.android.widgetapp.webmanual
pm uninstall -k --user 0 com.samsung.android.bixby.wakeup
pm uninstall -k --user 0 com.samsung.android.app.watchmanagerstub
pm uninstall -k --user 0 com.sec.android.deamonapp
pm uninstall -k --user 0 com.samsung.android.app.social
pm uninstall -k --user 0 com.microsoft.appmanager
pm uninstall -k --user 0 com.sec.android.autodoodle.service
pm uninstall -k --user 0 com.sec.android.app.clockpackage
pm uninstall -k --user 0 com.samsung.android.visionintelligence
pm uninstall -k --user 0 com.samsung.android.bixbyvision.framework
pm uninstall -k --user 0 com.samsung.android.app.contacts
pm uninstall -k --user 0 com.samsung.android.providers.contacts
pm uninstall -k --user 0 com.android.bips
pm uninstall -k --user 0 com.sec.android.app.samsungapps
pm uninstall -k --user 0 com.google.audio.hearing.visualization.accessibility.scribe
pm uninstall -k --user 0 com.samsung.android.game.gos
